# -*- coding: utf-8 -*-
"""forecast.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17OSdD_UTlA9HwMZJRqCOOZhmfdeCGQxV
"""



import sys
import math
import matplotlib.pyplot as plt
import keras
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import *
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping

print(len(sys.argv))
print(sys.argv)

# Read arguments given
# todo give maybe one more argument for window
time_series_num = 10 # default
for i in range(len(sys.argv)):
  if(sys.argv[i] == "-n"):
    time_series_num = int(sys.argv[i+1])
    break
print("number of time series given is:", time_series_num)

# Create data frame from our csv file
df=pd.read_csv("../../nasdaq2007_17.csv", header=None, delimiter='\t')

print(df.head(5))   #print first 5 rows

df = df.transpose() # transpose rows into columns


# todo choose random(?) time series



# Split data frame to training and test sets
# split = int(0.8*df.shape[0])
# training_set = df.iloc[:split, 1:2].values
# test_set = df.iloc[split:, 1:2].values